name: Build and Deploy Allure Report 3

on: 
  # push: 
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      ISSUE_KEY:
        description: 'Jira issue key to link in the report'
        required: false
        default: ''
      

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-allure-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable pnpm

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright
        # run: pnpm exec playwright install
        run: pnpm add -D @playwright/test playwright-core

      - name: Install playwright deps
        run: pnpm exec playwright install-deps

      - name: Install allure3
        run: pnpm install allure

      - name: Generate Allure Report
        run: | 
          pnpm allure run --config=./allurerc.mjs -- pnpm test
        env:
          ALLURE_JIRA_ISSUE: ${{ github.event.inputs.ISSUE_KEY }}
          ALLURE_JIRA_WEBHOOK: ${{ secrets.ALLURE_JIRA_WEBHOOK }}
          ALLURE_JIRA_TOKEN: ${{ secrets.ALLURE_JIRA_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './allure-report'
  deploy:
      needs: build-allure-report
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4